datasets:
- action: plot
  channels:
  - 00.BHZ
  folder: example/IU.ANMO..D
  output_folder: /tmp/ppsd_day_output
  plot_kwargs:
    cmap: pqlx
    cumulative: false
    grid: true
    show_coverage: true
    show_histogram: true
    show_mean: false
    show_mode: false
    show_noise_models: true
    show_percentiles: false
    xaxis_frequency: false
  response: example/IU_ANMO_RESP.xml
  timewindow: 600
  # Filter for daytime hours (06:00 to 22:00)
  time_filter:
    night_start: "06:00"
    night_stop: "22:00"
- action: plot
  channels:
  - 00.BHZ
  folder: example/IU.ANMO..D
  output_folder: /tmp/ppsd_night_output
  plot_kwargs:
    cmap: pqlx
    cumulative: false
    grid: true
    show_coverage: true
    show_histogram: true
    show_mean: false
    show_mode: false
    show_noise_models: true
    show_percentiles: false
    xaxis_frequency: false
  response: example/IU_ANMO_RESP.xml
  timewindow: 600
  # Filter for nighttime hours (22:00 to 06:00)
  time_filter:
    night_start: "22:00"
    night_stop: "06:00"
