PARAM_LABELS_EN = {
    "folder": "Data Folder",
    "response": "Response File",
    "channels": "Channels",
    "show_coverage": "Show Coverage",
    "show_percentiles": "Show Percentiles",
    "show_histogram": "Show Histogram",
    "percentiles": "Percentiles",
    "show_noise_models": "Show Noise Models",
    "show_earthquakes": "Show Earthquakes",
    "grid": "Show Grid",
    "max_percentage": "Max Percentage",
    "period_lim": "Period Limits",
    "show_mode": "Show Mode",
    "show_mean": "Show Mean",
    "cmap": "Colormap",
    "cumulative": "Cumulative",
    "cumulative_number_of_colors": "Cumulative Colors",
    "xaxis_frequency": "X Axis Frequency",
    "action": "Action",
    "timewindow": "Timewindow",
}

PARAM_TOOLTIPS_EN = {
    "channels": "List of channels (e.g. BHZ or 00.BHZ, one per line).",
    "action": "What to do: plot, calculate, full, or convert.",
    "timewindow": "Window length in seconds for PPSD calculation.",
    "show_coverage": "Show data coverage on the plot.",
    "show_percentiles": "Show percentiles on the plot.",
    "show_histogram": "Show histogram on the plot.",
    "percentiles": "Percentile values to plot (comma-separated).",
    "show_noise_models": "Show noise models (NLNM/NHNM).",
    "show_earthquakes": "Show earthquakes on the plot.",
    "grid": "Show grid lines.",
    "max_percentage": "Maximum percentage for color scale.",
    "period_lim": "Limits for period axis (e.g. 0.01, 179).",
    "show_mode": "Show mode value.",
    "show_mean": "Show mean value.",
    "cmap": "Colormap for the plot.",
    "cumulative": "Show cumulative distribution.",
    "cumulative_number_of_colors": "Number of colors for cumulative plot.",
    "xaxis_frequency": "Show frequency instead of period on x-axis.",
}

SOFTWARE_LABELS_EN = {
    "file": "File",
    "open": "Open",
    "exit": "Exit",
    "new_config": "New Configuration",
    "load_config": "Load Configuration",
    "save_config": "Save Configuration",
    "exit": "Exit",
    "add_dataset": "Add Dataset",
    "run_all": "Run All",
    "language": "Language",
    "dataset": "Dataset",
    "select_output": "Select Output Folder",
    "select": "Select",
    "delete": "Delete",
    "duplicate": "Duplicate",
    "run": "Run",
    "add": "Add dataset",
    "run_all_save": "Run All and Save Plots",
    "output_folder": "Output folder",
    "browse": "Browse",
    "img_size": "Image Size (inches):",
}

PARAM_LABELS_DE = {
    "folder": "Datenordner",
    "response": "Antwortdatei",
    "channels": "Kanäle",
    "show_coverage": "Abdeckung anzeigen",
    "show_percentiles": "Perzentile anzeigen",
    "show_histogram": "Histogramm anzeigen",
    "percentiles": "Perzentile",
    "show_noise_models": "Rauschmodelle anzeigen",
    "show_earthquakes": "Erdbeben anzeigen",
    "grid": "Gitter anzeigen",
    "max_percentage": "Maximaler Prozentsatz",
    "period_lim": "Periodengrenzen",
    "show_mode": "Modus anzeigen",
    "show_mean": "Mittelwert anzeigen",
    "cmap": "Farbskala",
    "cumulative": "Kumulativ",
    "cumulative_number_of_colors": "Farbenanzahl (kumulativ)",
    "xaxis_frequency": "X-Achse: Frequenz",
    "action": "Aktion",
    "timewindow": "Zeitfenster",
}

PARAM_TOOLTIPS_DE = {
    "channels": "Liste der Kanäle (z. B. BHZ oder 00.BHZ, jeweils eine pro Zeile).",
    "action": "Was soll getan werden: plot (zeichnen), calculate (berechnen), full (beides), oder convert (konvertieren).",
    "timewindow": "Fensterlänge in Sekunden für die PPSD-Berechnung.",
    "show_coverage": "Zeigt die Datenabdeckung im Diagramm.",
    "show_percentiles": "Zeigt Perzentilwerte im Diagramm.",
    "show_histogram": "Zeigt ein Histogramm im Diagramm.",
    "percentiles": "Perzentilwerte, die angezeigt werden sollen (kommagetrennt).",
    "show_noise_models": "Zeigt Rauschmodelle (NLNM/NHNM).",
    "show_earthquakes": "Zeigt Erdbeben im Diagramm.",
    "grid": "Gitterlinien im Diagramm anzeigen.",
    "max_percentage": "Maximaler Prozentsatz für die Farbskala.",
    "period_lim": "Grenzen der Periodenachse (z. B. 0.01, 179).",
    "show_mode": "Zeigt den Moduswert (häufigster Wert).",
    "show_mean": "Zeigt den Mittelwert.",
    "cmap": "Farbskala für das Diagramm.",
    "cumulative": "Zeigt kumulierte Verteilung.",
    "cumulative_number_of_colors": "Anzahl der Farben für das kumulierte Diagramm.",
    "xaxis_frequency": "Frequenz statt Periode auf der X-Achse anzeigen.",
}

SOFTWARE_LABELS_DE = {
    "file": "Datei",
    "open": "Öffnen",
    "exit": "Beenden",
    "new_config": "Neue Konfiguration",
    "load_config": "Konfiguration laden",
    "save_config": "Konfiguration speichern",
    "add_dataset": "Datensatz hinzufügen",
    "run_all": "Alle ausführen",
    "language": "Sprache",
    "dataset": "Datensatz",
    "select_output": "Zielordner auswählen",
    "select": "Auswählen",
    "delete": "Löschen",
    "duplicate": "Duplizieren",
    "run": "Ausführen",
    "add": "Datensatz hinzufügen",
    "run_all_save": "Alle ausführen und speichern",
    "output_folder": "Zielordner",
    "browse": "Durchsuchen",
    "img_size": "Bildgröße (Zoll):",
}

PARAM_LABELS_RU = {
    "folder": "Волновые формы",
    "response": "Файл отклика",
    "channels": "Каналы",
    "show_coverage": "Показать покрытие",
    "show_percentiles": "Показать процентильные уровни",
    "show_histogram": "Показать гистограмму",
    "percentiles": "Процентили",
    "show_noise_models": "Показать модели шума",
    "show_earthquakes": "Показать землетрясения",
    "grid": "Показать сетку",
    "max_percentage": "Макс. процент",
    "period_lim": "Пределы периода",
    "show_mode": "Показать моду",
    "show_mean": "Показать среднее",
    "cmap": "Цветовая карта",
    "cumulative": "Накопительное",
    "cumulative_number_of_colors": "Количество цветов (накопл.)",
    "xaxis_frequency": "Частота по оси X",
    "action": "Действие",
    "timewindow": "Временное окно",
}

PARAM_TOOLTIPS_RU = {
    "channels": "Список каналов (например, BHZ или 00.BHZ, по одному на строку).",
    "action": "Что делать: plot (график), calculate (расчет), full (оба), или convert (конвертировать).",
    "timewindow": "Длина временного окна в секундах для расчета PPSD.",
    "show_coverage": "Показать покрытие данных на графике.",
    "show_percentiles": "Показать процентильные уровни на графике.",
    "show_histogram": "Показать гистограмму на графике.",
    "percentiles": "Значения процентилей для отображения (через запятую).",
    "show_noise_models": "Показать модели шума (NLNM/NHNM).",
    "show_earthquakes": "Показать землетрясения на графике.",
    "grid": "Показать линии сетки.",
    "max_percentage": "Максимальный процент для цветовой шкалы.",
    "period_lim": "Пределы по оси периода (например, 0.01, 179).",
    "show_mode": "Показать наиболее частое значение (моду).",
    "show_mean": "Показать среднее значение.",
    "cmap": "Цветовая карта для графика.",
    "cumulative": "Показать накопленное распределение.",
    "cumulative_number_of_colors": "Количество цветов для накопленного графика.",
    "xaxis_frequency": "Показать частоту вместо периода по оси X.",
}

SOFTWARE_LABELS_RU = {
    "file": "Файл",
    "open": "Открыть",
    "exit": "Выход",
    "new_config": "Новая конфигурация",
    "load_config": "Загрузить конфигурацию",
    "save_config": "Сохранить конфигурацию",
    "add_dataset": "Добавить задачу",
    "run_all": "Запустить все",
    "language": "Язык",
    "dataset": "Задача",
    "select_output": "Выберите папку для сохранения",
    "select": "Выбрать",
    "delete": "Удалить",
    "duplicate": "Дублировать",
    "run": "Запустить",
    "add": "Добавить задачу",
    "options": "Опции построения",
    "run_all_save": "Запустить все задачи и сохранить",
    "output_folder": "Выбрать папку для сохранения",
    "browse": "Обзор",
    "img_size": "Размер изображения (дюймы):",
}

PARAM_LABELS_RS = {
    "folder": "Folder sa podacima",
    "response": "Odgovor fajl",
    "channels": "Kanali",
    "show_coverage": "Prikaži pokrivenost",
    "show_percentiles": "Prikaži percentile",
    "show_histogram": "Prikaži histogram",
    "percentiles": "Percentili",
    "show_noise_models": "Prikaži modele šuma",
    "show_earthquakes": "Prikaži zemljotrese",
    "grid": "Prikaži mrežu",
    "max_percentage": "Maksimalni procenat",
    "period_lim": "Granice perioda",
    "show_mode": "Prikaži mod",
    "show_mean": "Prikaži prosek",
    "cmap": "Mapa boja",
    "cumulative": "Kumulativno",
    "cumulative_number_of_colors": "Broj boja (kumulativno)",
    "xaxis_frequency": "X osa: frekvencija",
    "action": "Akcija",
    "timewindow": "Vremenski prozor",
}

PARAM_TOOLTIPS_RS = {
    "channels": "Lista kanala (npr. BHZ ili 00.BHZ, jedan po redu).",
    "action": "Šta raditi: plot (crtaj), calculate (izračunaj), full (oba), ili convert (konvertuj).",
    "timewindow": "Dužina vremenskog prozora u sekundama za PPSD.",
    "show_coverage": "Prikazuje pokrivenost podataka na grafikonu.",
    "show_percentiles": "Prikazuje percentile na grafikonu.",
    "show_histogram": "Prikazuje histogram na grafikonu.",
    "percentiles": "Vrednosti percentila za prikaz (odvojene zarezom).",
    "show_noise_models": "Prikazuje modele šuma (NLNM/NHNM).",
    "show_earthquakes": "Prikazuje zemljotrese na grafikonu.",
    "grid": "Prikazuje linije mreže.",
    "max_percentage": "Maksimalan procenat za obeležavanje bojama.",
    "period_lim": "Granice za osu perioda (npr. 0.01, 179).",
    "show_mode": "Prikazuje najčešću vrednost (mod).",
    "show_mean": "Prikazuje prosečnu vrednost.",
    "cmap": "Mapa boja za grafikon.",
    "cumulative": "Prikazuje kumulativnu distribuciju.",
    "cumulative_number_of_colors": "Broj boja za kumulativni grafikon.",
    "xaxis_frequency": "Prikazuj frekvenciju umesto perioda na X osi.",
}

SOFTWARE_LABELS_RS = {
    "file": "Fajl",
    "open": "Otvori",
    "exit": "Izlaz",
    "new_config": "Nova konfiguracija",
    "load_config": "Učitaj konfiguraciju",
    "save_config": "Sačuvaj konfiguraciju",
    "add_dataset": "Dodaj dataset",
    "run_all": "Pokreni sve",
    "language": "Jezik",
    "dataset": "Dataset",
    "select_output": "Izaberite izlazni folder",
    "select": "Izaberi",
    "delete": "Obriši",
    "duplicate": "Dupliraj",
    "run": "Pokreni",
    "add": "Dodaj dataset",
    "run_all_save": "Pokreni sve i sačuvaj grafikone",
    "output_folder": "Folder za čuvanje",
    "browse": "Pregledaj",
    "img_size": "Veličina slike (inči):",
}

PARAM_LABELS_TR = {
    "folder": "Veri Klasörü",
    "response": "Cevap Dosyası",
    "channels": "Kanallar",
    "show_coverage": "Kapsamı Göster",
    "show_percentiles": "Yüzdelikleri Göster",
    "show_histogram": "Histogramı Göster",
    "percentiles": "Yüzdelikler",
    "show_noise_models": "Gürültü Modellerini Göster",
    "show_earthquakes": "Depremleri Göster",
    "grid": "Izgara Göster",
    "max_percentage": "Maksimum Yüzde",
    "period_lim": "Periyot Sınırları",
    "show_mode": "Modu Göster",
    "show_mean": "Ortalama Göster",
    "cmap": "Renk Haritası",
    "cumulative": "Kümülatif",
    "cumulative_number_of_colors": "Kümülatif Renk Sayısı",
    "xaxis_frequency": "X Ekseninde Frekans",
    "action": "İşlem",
    "timewindow": "Zaman Penceresi",
}

PARAM_TOOLTIPS_TR = {
    "channels": "Kanal listesi (ör. BHZ veya 00.BHZ, her satıra bir tane).",
    "action": "Ne yapılacak: plot (çiz), calculate (hesapla), full (her ikisi), veya convert (dönüştür).",
    "timewindow": "PPSD hesaplaması için saniye cinsinden pencere uzunluğu.",
    "show_coverage": "Grafikte veri kapsamını göster.",
    "show_percentiles": "Grafikte yüzdelik değerleri göster.",
    "show_histogram": "Grafikte histogram göster.",
    "percentiles": "Gösterilecek yüzdelik değerler (virgülle ayrılmış).",
    "show_noise_models": "Gürültü modellerini göster (NLNM/NHNM).",
    "show_earthquakes": "Grafikte depremleri göster.",
    "grid": "Izgara çizgilerini göster.",
    "max_percentage": "Renk ölçeği için maksimum yüzde.",
    "period_lim": "Periyot ekseni sınırları (ör. 0.01, 179).",
    "show_mode": "Mod değerini göster.",
    "show_mean": "Ortalama değeri göster.",
    "cmap": "Grafik için renk haritası.",
    "cumulative": "Kümülatif dağılımı göster.",
    "cumulative_number_of_colors": "Kümülatif grafik için renk sayısı.",
    "xaxis_frequency": "X ekseninde periyot yerine frekans göster.",
}

SOFTWARE_LABELS_TR = {
    "file": "Dosya",
    "open": "Aç",
    "exit": "Çıkış",
    "new_config": "Yeni Yapılandırma",
    "load_config": "Yapılandırmayı Yükle",
    "save_config": "Yapılandırmayı Kaydet",
    "add_dataset": "Veri Kümesi Ekle",
    "run_all": "Hepsini Çalıştır",
    "language": "Dil",
    "dataset": "Veri Kümesi",
    "select_output": "Çıktı Klasörünü Seç",
    "select": "Seç",
    "delete": "Sil",
    "duplicate": "Kopyala",
    "run": "Çalıştır",
    "add": "Veri kümesi ekle",
    "run_all_save": "Hepsini çalıştır ve grafikleri kaydet",
    "output_folder": "Çıktı klasörü",
    "browse": "Gözat",
    "img_size": "Görsel Boyutu (inç):",
    "progress": "İlerleme",
}

ALL_LABELS = {
    "EN": PARAM_LABELS_EN,
    "DE": PARAM_LABELS_DE,
    "RU": PARAM_LABELS_RU,
    "RS": PARAM_LABELS_RS,
    "TR": PARAM_LABELS_TR
}

ALL_TOOLTIPS = {
    "EN": PARAM_TOOLTIPS_EN,
    "DE": PARAM_TOOLTIPS_DE,
    "RU": PARAM_TOOLTIPS_RU,
    "RS": PARAM_TOOLTIPS_RS,
    "TR": PARAM_TOOLTIPS_TR
}

ALL_SOFTWARE_LABELS = {
    "EN": SOFTWARE_LABELS_EN,
    "DE": SOFTWARE_LABELS_DE,
    "RU": SOFTWARE_LABELS_RU,
    "RS": SOFTWARE_LABELS_RS,
    "TR": SOFTWARE_LABELS_TR
}
